fp/playback/flask_app/main/routes.py
from flask import Blueprint, render_template, url_for, redirect, request
from ..models import User, Review
from flask_login import current_user
from ..utils import current_time
import base64,io

from .. import spotify_client
from ..forms import SearchForm, AlbumReviewForm

def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image


main = Blueprint("main", __name__)

@main.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        return redirect(url_for("main.query_results", query=form.search_query.data))
    
    return render_template("index.html", form=form)

@main.route("/search-results/<query>", methods = ["GET"])
def query_results(query):
    try:
        results = spotify_client.seach_for_artist_info(query)
    except ValueError as e:
        return render_template("query.html", error_msg=str(e))

    return render_template("query.html", results=results)

@main.route("/artists/<artist_id>", methods=["GET"])
def artist_detail(artist_id):
    try:
        artist_name = spotify_client.get_artist_info_by_artist_id(artist_id)["name"]
        artist_albums = spotify_client.get_albums_info_by_artist_id(artist_id)
    except ValueError as e:
        return render_template("artist_detail.html", error_msg=str(e))
    return render_template("artist_detail.html", artist_name=artist_name, artist_albums=artist_albums)

@main.route("/albums/<album_id>", methods=["GET", "POST"])
def album_detail(album_id):
    try:
        tracks = spotify_client.get_track_info_by_album_id(album_id)
        album_name = spotify_client.get_album_info_by_album_id(album_id)["name"]
        album_art = spotify_client.get_album_info_by_album_id(album_id)["images"][0]["url"]
        access_token = spotify_client.get_access_token()
    except ValueError as e:
        return render_template("album_detail.html", error_msg=str(e))
    
    form = AlbumReviewForm()
    if form.validate_on_submit():
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            album_id=album_id,
            album_title=album_name,
        )

        review.save()

        return redirect(request.path)

    reviews = Review.objects(album_id=album_id)

    return render_template("album_detail.html", tracks=tracks, 
                           album_name=album_name, reviews=reviews, 
                           form=form, album_art=album_art, 
                           access_token=access_token)

@main.route("/user/<username>")
def user_detail(username):
    #uncomment to get review image
    #user = find first match in db
    user = User.objects(username=username).first()
    #img = get_b64_img(user.username) use their username for helper function
    img = get_b64_img(user.username)
    error = None
    return render_template('user_detail.html', image = img, error = error, username=username)

fp/playback/flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64, io
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User

users = Blueprint("users", __name__)

""" ************ User Management views ************ """


# TODO: implement
@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        print("already logged in")
        return redirect(url_for('main.index'))
    
    form= RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, 
                    email=form.email.data, password=hashed)
        user.save()
        return redirect(url_for('users.login'))

    return render_template('register.html', form= form)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if (user is not None and 
            bcrypt.check_password_hash(user.password, form.password.data)):
            login_user(user)
            return redirect(url_for('users.account'))
        else:
            flash('Login failed. Check your username and/or password')

    return render_template('login.html', form= form)


# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    if request.method == "POST":
        if update_username_form.submit_username.data and update_username_form.validate():
            new_username = update_username_form.username.data
            # TODO: handle update username form submit
            current_user.username = new_username
            current_user.save()
            return redirect(url_for('users.login'))

        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            # TODO: handle update profile pic form submit
            #pass
            img = update_profile_pic_form.picture.data
            filename = secure_filename(img.filename)
            content_type = f'images/{filename[-3:]}'

            if current_user.profile_pic.get() is None:
                current_user.profile_pic.put(img.stream, content_type=content_type)
            else:
                current_user.profile_pic.replace(img.stream, content_type=content_type)
            current_user.save()
            return redirect(url_for('users.account'))



    # TODO: handle get requests
    return render_template('account.html', update_username_form= update_username_form, 
                           update_profile_pic_form= update_profile_pic_form, username=current_user.username,
                           image = get_b64_img(current_user.username))

def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

fp/playback/flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div>
    <!-- Greeting -->
    {% if image %}
        {# Profile picture #}
        <img src="data:image/png;base64,{{image}}" alt="image">
    {% endif %}

    <div>Welcome, {{username}}!</div>

    <!-- update username -->
    <div>
        <h3>
            Update Username
        </h3>
        <form method="POST" action="">
            {{ update_username_form.csrf_token }}
            <div>
                {{ update_username_form.username.label }}
                {{ update_username_form.username(class="form-content") }}
                {% if update_username_form.username.errors %}
                <div role="alert">
                    {% for error in update_username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {{ update_username_form.submit_username }}
        </form>
    </div>

    <!-- update profile pic -->
    <div>
        Update Profile Picture
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label }}
            {{ update_profile_pic_form.picture(class="form-content") }}
            {% if update_profile_pic_form.picture.errors %}
            <div role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture }}
    </form>

</div>
{% endblock %}

fp/playback/flask_app/templates/album_detail.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}
<div>information for {{ album_name }}</div>
<img src="{{album_art}}"><img>
<div>tracks</div>
<ul>
    {% for track in tracks %}
    <li>{{track["name"]}}</li>
    {% endfor %}
</ul>

{# Reviews #}
<div>
  <div> Reviews
    <div> {{ reviews | length }} reviews </div>
  </div>
  <ul>
    {% for review in reviews %}
      <li>
        <img src="data:image/png;base64,{{review.image}}" alt="" />
        <div>
          <span>{{ review.date }}</span>
          <a href="{{ url_for('main.user_detail', username=review.commenter.username) }}">
            @{{ review.commenter.username }}
          </a>
          <p>{{ review.content }}</p>
        </div>
      </li>
    {% endfor %}
  </ul>

  {% if current_user.is_authenticated %}
    {# Movie review submission form #}
    <div>
      <form method="POST" action="" class="review-form">
        {{ form.csrf_token }}
        <div>
          {{ form.text.label }} {{ form.text(class="form-content") }}
          {% if form.text.errors %}
            <div class="error" role="alert">
              {% for error in form.text.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
      </form>
    </div>
  {% endif %}
</div>

<button id="togglePlay">Toggle Play</button>

<script src="https://sdk.scdn.co/spotify-player.js"></script>
<script>
  window.onSpotifyWebPlaybackSDKReady = () => {
    const token = '[My Spotify Web API access token]';
    const player = new Spotify.Player({
      name: 'Web Playback SDK Quick Start Player',
      getOAuthToken: cb => { cb(token); }
    });
  }
</script>

{% endblock content %}

fp/playback/flask_app/templates/artist_detail.html
{% extends "header.html" %} {% block content %}

{% if error_msg %}
  <b class="text-red-400">
    {{ error_msg }}
  </b>
{% endif %}

<div>information for {{artist_name}}</div>
<div>albums</div>
<ul>
{% for album in artist_albums %}
    <li><a href="{{ url_for('main.album_detail', album_id=album['id']) }}">{{album["name"]}}</a></li>
{% endfor %}
</ul>
{% endblock content %}

fp/playback/flask_app/templates/base.html
<html lang="en">
<head>
    <link rel="shortcut icon" href=" {{url_for('static', filename='goat.ico')}} ">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>playback</title>
    {% endif %}
</head>
<body>
    {% block header %}
    
    {% endblock %}
</body>
</html>

fp/playback/flask_app/templates/header.html
{% extends "base.html" %} 

{% block header %}

<nav>
    <a href = "{{ url_for('main.index') }}">playback</a>

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('users.account') }}">Account</a>
    <a href="{{ url_for('users.logout') }}">Logout</a>
    {% else %}
    <a href="{{ url_for('users.login') }}">Login</a>
    <a href="{{ url_for('users.register') }}">Register</a>
    {% endif %}
</nav>

{% block content %}
{% endblock %}

{% endblock %}

fp/playback/flask_app/templates/index.html
{% extends "header.html" %} {% block content %}
<div>
    <div>search artist</div>
    <form action = "/" method = "POST">
        {{ form.csrf_token }}
        {{ form.search_query(class="form-control", placeholder="search") }}
        {% if form.search_query.errors %}
            <div>
                {% for error in form.search_query.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% endif %}
      
        {{ form.submit(class="form-button") }}
    </form>
</div>
{% endblock %}

fp/playback/flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
    <div>login</div>
    <div>
        if you don't have an account already, <a href="{{ url_for('users.register') }}">register here</a>
    </div>

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit }}
    </form>

{% endblock %}

fp/playback/flask_app/templates/query.html
{% extends "header.html" %} {% block content %}
    
    {% if error_msg %}
        <b class="text-red-400">
        {{ error_msg }}
        </b>
    {% endif %}

    <div>artists</div>
    <ul>
        {% for artist in results %}
        <li>
            <a href="{{ url_for('main.artist_detail', artist_id=artist['id']) }}">{{artist["name"]}}</a>
        </li>
        {% endfor %}
    </ul>
  


{% endblock %}

fp/playback/flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}

<div>registration</div>
<div>if you already have an account, <a href="{{ url_for('users.login') }}">login here</a> </div>

<form method="POST" action="">
    {{ form.csrf_token }}
    <div review-input">
        {{ form.username.label }}
        {{ form.username(class="form-content") }}
        {% if form.username.errors %}
        <div role="alert">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div>
        {{ form.email.label }}
        {{ form.email }}
        {% if form.email.errors %}
        <div class="error" role="alert">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }}
        {{ form.password }}
        {% if form.password.errors %}
        <div role="alert">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div>
        {{ form.confirm_password.label }}
        {{ form.confirm_password }}
        {% if form.confirm_password.errors %}
        <div role="alert">
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    {{ form.submit }}
</form>

{% endblock %}

fp/playback/flask_app/templates/user_detail.html
{% extends "header.html" %} {% block content %}
{% if error %}
    <b role="alert">
        {{ error }}
    </b>
{% endif %}
<div>
    {# User's Profile Picture #}
    <img src="data:image/png;base64,{{image}}" alt="image">
    <h2>{{username}}'s Reviews</h2>

</div>
<div>
    {# TODO: Show all reviews made by the user #}

</div>
{% endblock %}